import { makeStyles } from '@material-ui/core/styles'
import { sidebarColors } from '../layout/sidebarStyles'

const styles = makeStyles((theme) => ({
  root: {
    minHeight: '100%',
    width: '100%',
    boxSizing: 'border-box',
    padding: theme.spacing(3),
    color: sidebarColors.text,
    backgroundColor: sidebarColors.background,
    fontFamily: "system-ui, 'Helvetica Neue', Helvetica, Arial, sans-serif",
    [theme.breakpoints.down('xs')]: { padding: theme.spacing(2) },
  },
  content: {
    width: '100%',
    maxWidth: 1180,
    margin: '0 auto',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: theme.spacing(2),
    marginBottom: theme.spacing(2),
    position: 'relative',
    zIndex: 1,
  },
  brand: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: theme.spacing(1),
    minWidth: 0,
    color: `${sidebarColors.text} !important`,
    textDecoration: 'none',
    fontSize: '1.2rem',
    fontWeight: 700,
    letterSpacing: '-0.02em',
  },
  brandMark: {
    width: 32,
    height: 24,
    flexShrink: 0,
    color: sidebarColors.accent,
  },
  sectionNav: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: theme.spacing(0.5),
    padding: 4,
    borderRadius: 16,
    backgroundColor: 'rgba(255,255,255,.045)',
  },
  sectionLink: {
    minHeight: 36,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '0 14px',
    borderRadius: 12,
    color: `${sidebarColors.navigation} !important`,
    textDecoration: 'none',
    fontSize: 14,
    fontWeight: 600,
    '&[aria-current="page"]': {
      color: `${sidebarColors.activeText} !important`,
      backgroundColor: sidebarColors.selection,
    },
    '&:focus-visible': {
      outline: `2px solid ${sidebarColors.accent}`,
      outlineOffset: 2,
    },
  },
  titleBlock: {
    margin: `${theme.spacing(1)}px 0 ${theme.spacing(2)}px`,
  },
  eyebrow: {
    margin: 0,
    color: sidebarColors.accent,
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: '0.14em',
    textTransform: 'uppercase',
  },
  title: {
    margin: `${theme.spacing(0.5)}px 0 0`,
    color: sidebarColors.text,
    fontSize: 'clamp(1.6rem, 4vw, 2.6rem)',
    lineHeight: 1.1,
    letterSpacing: '-0.045em',
  },
  subtitle: {
    margin: `${theme.spacing(1)}px 0 0`,
    color: sidebarColors.secondary,
    fontSize: 14,
  },
  actions: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    flexWrap: 'wrap',
    gap: theme.spacing(1),
  },
  button: {
    minHeight: 38,
    padding: '7px 15px',
    border: `1px solid ${sidebarColors.divider}`,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,.05)',
    color: `${sidebarColors.text} !important`,
    font: 'inherit',
    fontSize: 14,
    fontWeight: 650,
    cursor: 'pointer',
    '&:hover': { backgroundColor: sidebarColors.selection },
    '&:disabled': {
      color: `${sidebarColors.secondary} !important`,
      cursor: 'wait',
      opacity: 0.72,
    },
    '&:focus-visible': {
      outline: `2px solid ${sidebarColors.accent}`,
      outlineOffset: 2,
    },
  },
  primaryButton: {
    backgroundColor: sidebarColors.accent,
    borderColor: sidebarColors.accent,
    color: '#fff !important',
    '&:hover': { backgroundColor: '#e61f70' },
  },
  iconButton: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 38,
    padding: 0,
    '& svg': { width: 20, height: 20 },
  },
  '@keyframes spin': {
    from: { transform: 'rotate(0deg)' },
    to: { transform: 'rotate(360deg)' },
  },
  spinner: {
    width: 18,
    height: 18,
    animation: '$spin 850ms linear infinite',
  },
  refreshIndicator: {
    width: 30,
    height: 30,
    color: sidebarColors.accent,
    opacity: 0,
    transition: 'opacity 120ms ease, transform 120ms ease',
    pointerEvents: 'none',
  },
  refreshIndicatorActive: { opacity: 1 },
  refreshIndicatorSpinning: { animation: '$spin 850ms linear infinite' },
  feedGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    gap: theme.spacing(2.5),
    [theme.breakpoints.down('sm')]: {
      gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
      gap: theme.spacing(1.5),
    },
    [theme.breakpoints.down('xs')]: {
      gridTemplateColumns: 'minmax(0, 1fr)',
      gap: theme.spacing(1.5),
    },
  },
  feedCard: {
    minWidth: 0,
    overflow: 'hidden',
    borderRadius: 16,
    backgroundColor: 'rgba(255,255,255,.045)',
    transition: 'transform 120ms ease, background-color 120ms ease',
    '&:hover': {
      transform: 'translateY(-2px)',
      backgroundColor: sidebarColors.selection,
    },
    '@media (prefers-reduced-motion: reduce)': { transition: 'none' },
  },
  cardButton: {
    display: 'block',
    width: '100%',
    padding: 0,
    border: 0,
    background: 'transparent',
    color: 'inherit',
    textAlign: 'left',
    font: 'inherit',
    cursor: 'pointer',
    '&:focus-visible': {
      outline: `2px solid ${sidebarColors.accent}`,
      outlineOffset: -2,
      borderRadius: 16,
    },
  },
  thumbnail: {
    position: 'relative',
    aspectRatio: '16 / 9',
    overflow: 'hidden',
    backgroundColor: sidebarColors.divider,
  },
  thumbnailImage: {
    display: 'block',
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  thumbnailPlaceholder: {
    width: '100%',
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: sidebarColors.secondary,
    fontWeight: 700,
    fontSize: 34,
  },
  badge: {
    position: 'absolute',
    right: 8,
    bottom: 8,
    padding: '2px 6px',
    borderRadius: 5,
    backgroundColor: 'rgba(0,0,0,.78)',
    color: '#fff',
    fontSize: 11,
    fontWeight: 700,
  },
  liveBadge: {
    position: 'absolute',
    left: 8,
    top: 8,
    padding: '3px 6px',
    borderRadius: 5,
    backgroundColor: '#d51d4f',
    color: '#fff',
    fontSize: 10,
    fontWeight: 800,
    letterSpacing: '0.08em',
  },
  watchProgress: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 4,
    backgroundColor: sidebarColors.accent,
    transformOrigin: 'left center',
  },
  cardBody: { padding: theme.spacing(1.5) },
  cardTitle: {
    display: '-webkit-box',
    margin: 0,
    overflow: 'hidden',
    color: sidebarColors.text,
    fontSize: 15,
    fontWeight: 700,
    lineHeight: 1.28,
    WebkitBoxOrient: 'vertical',
    WebkitLineClamp: 2,
  },
  cardMeta: {
    margin: `${theme.spacing(0.5)}px 0 0`,
    overflow: 'hidden',
    color: sidebarColors.secondary,
    fontSize: 12,
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  statusRow: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: theme.spacing(1),
    marginTop: theme.spacing(1),
    color: sidebarColors.secondary,
    fontSize: 11,
  },
  empty: {
    maxWidth: 560,
    margin: `${theme.spacing(5)}px auto`,
    padding: theme.spacing(4),
    border: `1px solid ${sidebarColors.divider}`,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,.035)',
    textAlign: 'center',
  },
  emptyTitle: { margin: 0, color: sidebarColors.text, fontSize: 22 },
  emptyText: {
    margin: `${theme.spacing(1)}px 0 ${theme.spacing(2)}px`,
    color: sidebarColors.secondary,
  },
  state: {
    display: 'flex',
    minHeight: 180,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
    gap: theme.spacing(1),
    color: sidebarColors.secondary,
    textAlign: 'center',
  },
  stateTitle: { margin: 0, color: sidebarColors.text, fontSize: 20 },
  stateText: { maxWidth: 520, margin: 0, fontSize: 14 },
  alert: {
    margin: `${theme.spacing(1.5)}px 0`,
    padding: `${theme.spacing(1)}px ${theme.spacing(1.5)}px`,
    border: '1px solid rgba(255,100,140,.35)',
    borderRadius: 10,
    backgroundColor: 'rgba(255,42,127,.1)',
    color: '#ffb5cd',
    fontSize: 13,
  },
  channelList: { display: 'grid', gap: theme.spacing(1.25) },
  channelRow: {
    display: 'flex',
    alignItems: 'center',
    gap: theme.spacing(1.5),
    minWidth: 0,
    padding: theme.spacing(1.25),
    borderRadius: 15,
    backgroundColor: 'rgba(255,255,255,.045)',
    color: `${sidebarColors.text} !important`,
    textDecoration: 'none',
    '&:hover': { backgroundColor: sidebarColors.selection },
    '&:focus-visible': {
      outline: `2px solid ${sidebarColors.accent}`,
      outlineOffset: 2,
    },
  },
  avatar: {
    position: 'relative',
    width: 52,
    height: 52,
    flexShrink: 0,
    overflow: 'hidden',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '50%',
    backgroundColor: sidebarColors.divider,
    color: sidebarColors.activeText,
    fontSize: 20,
    fontWeight: 800,
  },
  channelCopy: { minWidth: 0, flex: 1 },
  channelName: {
    display: 'block',
    overflow: 'hidden',
    fontSize: 15,
    fontWeight: 700,
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  channelMeta: {
    display: 'block',
    marginTop: 3,
    overflow: 'hidden',
    color: sidebarColors.secondary,
    fontSize: 12,
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  chevron: { color: sidebarColors.secondary, fontSize: 26, lineHeight: 1 },
  form: {
    display: 'flex',
    alignItems: 'flex-end',
    gap: theme.spacing(1),
    margin: `${theme.spacing(2)}px 0 ${theme.spacing(3)}px`,
    [theme.breakpoints.down('xs')]: {
      alignItems: 'stretch',
      flexDirection: 'column',
    },
  },
  formField: {
    flex: 1,
    minWidth: 0,
    '& label': {
      display: 'block',
      marginBottom: 6,
      color: sidebarColors.secondary,
      fontSize: 12,
      fontWeight: 600,
    },
    '& input': {
      width: '100%',
      boxSizing: 'border-box',
      minHeight: 40,
      padding: '8px 11px',
      border: `1px solid ${sidebarColors.divider}`,
      borderRadius: 10,
      outline: 'none',
      backgroundColor: 'rgba(255,255,255,.045)',
      color: sidebarColors.text,
      font: 'inherit',
      '&:focus': {
        borderColor: sidebarColors.accent,
        boxShadow: `0 0 0 2px ${sidebarColors.selection}`,
      },
    },
  },
  channelIdentity: {
    display: 'flex',
    alignItems: 'center',
    gap: theme.spacing(1.5),
    margin: `${theme.spacing(1)}px 0 ${theme.spacing(2)}px`,
    [theme.breakpoints.down('xs')]: {
      alignItems: 'flex-start',
      flexWrap: 'wrap',
    },
  },
  identityAvatar: { width: 64, height: 64, fontSize: 26 },
  identityCopy: { minWidth: 0, flex: 1 },
  identityTitle: {
    margin: 0,
    overflow: 'hidden',
    color: sidebarColors.text,
    fontSize: 'clamp(1.35rem, 4vw, 2.1rem)',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  identityMeta: {
    margin: '4px 0 0',
    color: sidebarColors.secondary,
    fontSize: 13,
  },
  importProgress: { margin: `${theme.spacing(1.5)}px 0 ${theme.spacing(2)}px` },
  progressLabel: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: theme.spacing(1),
    marginBottom: 5,
    color: sidebarColors.secondary,
    fontSize: 12,
  },
  progress: {
    width: '100%',
    height: 7,
    accentColor: sidebarColors.accent,
  },
  videoGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    gap: theme.spacing(2),
    [theme.breakpoints.down('sm')]: {
      gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    },
    [theme.breakpoints.down('xs')]: { gridTemplateColumns: 'minmax(0, 1fr)' },
  },
  videoCard: {
    minWidth: 0,
    overflow: 'hidden',
    borderRadius: 15,
    backgroundColor: 'rgba(255,255,255,.045)',
  },
  videoBody: { padding: theme.spacing(1.5) },
  cardActions: {
    display: 'flex',
    gap: theme.spacing(1),
    marginTop: theme.spacing(1.25),
  },
  actionButton: { flex: 1, minWidth: 0, textAlign: 'center' },
  errorText: {
    margin: `${theme.spacing(0.75)}px 0 0`,
    color: '#ff9dbc',
    fontSize: 12,
  },
  loadMore: { display: 'block', margin: `${theme.spacing(2.5)}px auto 0` },
  downloadProgress: { marginTop: theme.spacing(1.25) },
}))

export default styles
